#API endpoints
event_api = 'https://gamma-api.polymarket.com/events'
tag_api = 'https://gamma-api.polymarket.com/tags'
transaction_api = 'https://data-api.polymarket.com/trades'
holders_api = 'https://data-api.polymarket.com/holders'
activity_api = 'https://data-api.polymarket.com/activity'
positions_api = 'https://data-api.polymarket.com/v1/market-positions'

#Names for DB
db_name = 'polymarket_data.db'

#only calls markets with the selected tag slug. Tag slugs are a text tag
#using number tag ids will fail
#This arguement expects a list.
tag_slug = ['derivatives', 'pop-culture', 'syracuse']

#Determines if the calls return comments
#This script has not been tested with comments
#Put another way, if this is set to true it will probably not work
include_chat = 'false'

#used to dertermine if transactions are only collected for users in both markets
#needs to be a boolean
in_both = true

#=============
#conditionIds
#=============
#used to determine what market you will get transactions from
#market_to_collect is used by collect_transactions to determine which market it will be collecting from
#derivative market is the condition id for the derivative market and market underlying is for the
#market backing the derivative asset 
market_to_collect = '0x0b4cc3b739e1dfe5d73274740e7308b6fb389c5af040c3a174923d928d134bee'
derivative_market = '0xc1588218a290e61ef35545553b157f76702cc3c61f7f1d309a9c68a49cbc29fd'
market_underlying = '0x0b4cc3b739e1dfe5d73274740e7308b6fb389c5af040c3a174923d928d134bee'

#Names for views to be analyzed
underlying_view_name = 'will_jesus_christ_return_before_2027'
derivative_view_name = 'jesus_christ_return_before_2027_odds_5_monday_night_12_1_am'

#Pickle file for holders name
holders_pickle_name = 'holders.pkl'

#names for output tables
[table_names]
event_table_name = 'events'
market_table_name = 'markets'
tag_table_name = 'tags'
tag_bridge_table_name = 'tag_event_bridge'
transaction_table_name = 'transactions'


#Determines if the script calls inactive and closed markets
#true and false will call both
[market_status]
active = ['true', 'false']
closed = ['true', 'false']



